version: '3'

services:
  mysql:
    image: mysql:latest
#    command:
#      - '--character-set-server=utf8mb4'
    restart: unless-stopped
    tty: true
    container_name: sql-weekends
    ports:
      - "3306:3306"
    volumes:
      - .:/var/lib
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: sql-weekends
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret